#!/bin/bash

## Description: Launch a browser and login to the current Drupal project.
## Usage: login [--name=USER]
## Example: "ddev login" or "ddev login --name=username" or "ddev login --uid=1"

FULLURL=$(ddev drush uli ${1} | tr -d '\r')

case $OSTYPE in
  linux-gnu)
    xdg-open "${FULLURL}"
    ;;
  "darwin"*)
    open "${FULLURL}"
    ;;
  "win*"* | "msys"*)
    start "${FULLURL}"
    ;;
esac
