#ddev-generated
# Simple template to demonstrate drupal-rfs-custom-commands
services:
  drupal-rfs-custom-commands:
    container_name: ddev-${DDEV_SITENAME}-drupal-rfs-custom-commands
    image: busybox:stable
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
