#!/bin/bash

## #ddev generated

## Description: Run PHPUnit tests inside the web container.
## Usage: phpunit
## Example: "ddev phpunit" or with additional arguments such as "ddev phpunit --help"

echo 'Running PHPUnit...'
vendor/bin/phpunit $*
